name: Daily Aplaybox Check

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install distutils
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected-chromedriver selenium

    - name: Run Aplaybox Checker
      env:
        APLAYBOX_COOKIE: ${{ secrets.APLAYBOX_COOKIE }}
      run: |
        python aplaybox_checker.py